# STEEL — the publication kernel, under artafather.
#
# One public notebook whose run produces the exact published files: the mastered song, its
# lossless master, the 3000px artwork, and the seamless animated cover loop. Nothing is generated
# here that was not generated by a public, re-runnable kernel — the song came from the STEEL
# render (gated on register and intelligibility, mastered by measured A/B) and the cover loop from
# LTX-Video conditioned at both endpoints. This kernel gathers those public outputs, verifies them
# once more on the delivered bytes, and lays them out for submission.
#
# Why gather rather than regenerate: the song took ~14 GPU-minutes and the loop ~2, and both are
# already public and hash-verifiable. Re-rolling them would produce DIFFERENT audio (the sampler
# is seeded but the environment is not byte-frozen) and break the link between what was verified
# and what is published. Provenance beats tidiness.
import hashlib, json, os, shutil, subprocess, sys
from pathlib import Path

WORK = Path("/kaggle/working")
OUT = WORK / "out"; OUT.mkdir(parents=True, exist_ok=True)

def sh(c, quiet=False):
    if not quiet: print(f"$ {c[:140]}", flush=True)
    r = subprocess.run(c, shell=True, text=True, capture_output=True)
    if r.stdout.strip() and not quiet: print(r.stdout[-800:], flush=True)
    if r.returncode: print("ERR:", r.stderr[-800:], flush=True)
    return r.returncode

sh("pip install -q numpy soundfile 2>&1 | tail -1")
import glob as _g
import numpy as np

def find(pat):
    hits = sorted(_g.glob(f"/kaggle/input/**/{pat}", recursive=True))
    return hits[0] if hits else None

SRC = {
    "STEEL.mp3": find("STEEL.mp3"),
    "STEEL.wav": find("STEEL.wav"),
    "cover_3000.png": find("cover_3000.png"),
    "STEEL_cover_loop.webm": find("STEEL_cover_loop.webm"),
    "STEEL_cover_loop.mp4": find("STEEL_cover_loop.mp4"),
}
for k, v in SRC.items():
    print(f"  {k:26s} {v or 'MISSING'}", flush=True)
missing = [k for k, v in SRC.items() if not v]
assert not missing, f"inputs not mounted: {missing}"

manifest = {}
for name, path in SRC.items():
    dst = OUT / name
    shutil.copy(path, dst)
    h = hashlib.sha256()
    with open(dst, "rb") as f:
        for c in iter(lambda: f.read(1 << 22), b""):
            h.update(c)
    manifest[name] = {"bytes": dst.stat().st_size, "sha256": h.hexdigest()}
    print(f"  {name:26s} {dst.stat().st_size/1048576:7.2f} MB  {h.hexdigest()[:16]}", flush=True)

# ── verify the delivered audio, on the bytes that ship ──────────────────────────────────
def loudness(p):
    out = subprocess.run(["ffmpeg", "-hide_banner", "-nostats", "-i", str(p),
                          "-filter_complex", "ebur128=peak=true", "-f", "null", "-"],
                         capture_output=True, text=True).stderr
    tail = out[out.rfind("Summary"):] if "Summary" in out else ""
    g = lambda k: next((float(l.split()[1]) for l in tail.splitlines()
                        if l.strip().startswith(k)), None)
    return {"lufs": g("I:"), "lra_lu": g("LRA:"), "true_peak_dbtp": g("Peak:")}

import soundfile as sf
audio, sr = sf.read(str(OUT / "STEEL.wav"))
clipped = int((np.abs(audio) >= 0.99996).sum())
checks = {"audio": {**loudness(OUT / "STEEL.mp3"), "clipped": clipped,
                    "seconds": round(len(audio) / sr, 2), "sample_rate": sr}}

# ── verify the delivered loop, including the wrap a player actually shows ───────────────
sh(f"ffmpeg -v error -i '{OUT/'STEEL_cover_loop.webm'}' -vf scale=256:176 "
   f"-f rawvideo -pix_fmt rgb24 /tmp/_v.rgb -y", quiet=True)
v = np.fromfile("/tmp/_v.rgb", dtype=np.uint8).reshape(-1, 176, 256, 3).astype(np.float32) / 255
luma = 0.2126*v[...,0] + 0.7152*v[...,1] + 0.0722*v[...,2]
dmean = np.abs(np.diff(luma.reshape(len(v), -1).mean(1)))
per_frame = np.abs(np.diff(luma, axis=0)).reshape(len(v)-1, -1).mean(1) * 255
wrap = float(np.abs(luma[-1] - luma[0]).mean() * 255)
typical = float(np.percentile(per_frame, 95))
checks["cover_loop"] = {
    "frames": int(len(v)), "cuts": int((dmean > 0.10).sum()),
    "ti_mean": round(float(per_frame.mean()), 2),
    "wrap_delta": round(wrap, 2), "typical_frame_delta": round(typical, 2),
    "wrap_ratio": round(wrap / max(typical, 1e-6), 2)}

(WORK / "manifest.json").write_text(json.dumps({"files": manifest, "checks": checks}, indent=2))
print("\n" + json.dumps(checks, indent=2), flush=True)

assert checks["audio"]["clipped"] == 0, "clipped samples in the master"
assert checks["cover_loop"]["cuts"] == 0, "the cover loop cuts"
assert checks["cover_loop"]["wrap_ratio"] < 2.5, "the loop wrap is visible"
print("\nSTEEL: verified on the delivered bytes, ready to publish", flush=True)
sh(f"ls -la {OUT}")
